version: '3.8'
services:
  backend:
    container_name: backend
    build:
      context: ./game/backend
    dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./game/backend:/usr/src/app
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/mydatabase
    depends_on:
      - db

  frontend:
    container_name: frontend
    build:
      context: ./game/frontend
    dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./game/frontend:/usr/src/app
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - backend

  db:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docs/entrega2/assets:/docker-entrypoint-initdb.d

volumes:
  pgdata: