version: '3.8'

services:
  database:
    image: postgres:13
    container_name: alice_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend

  app:
    build: ./game/backend
    container_name: alice_app
    environment:
      DB_HOST: database
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - database
    volumes:
      - ./game/backend:/usr/src/app
    networks:
      - backend
    command: bash -c "npm install && node src/app.js"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - database
    networks:
      - backend

volumes:
  postgres-data:
  pgadmin-data:

networks:
  backend: